-- *** KS PERMISSION TYPES ***
--College
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR) 
  VALUES ('Y', KRIM_TYP_ID_S.NEXTVAL, 'College Type','KS-LUM',sys_guid(),'kimRoleTypeService',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,LBL,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.student.bo.KualiStudentKimAttributes',KRIM_ATTR_DEFN_ID_S.NEXTVAL,'college','College','KS-LUM',sys_guid(),1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR) 
  VALUES ('Y',KRIM_ATTR_DEFN_ID_S.CURRVAL,KRIM_TYP_ATTR_ID_S.NEXTVAL,KRIM_TYP_ID_S.CURRVAL,sys_guid(),'a',1)
/


--Department
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR) 
  VALUES ('Y',KRIM_TYP_ID_S.NEXTVAL,'Department Type','KS-LUM',sys_guid(),'kimRoleTypeService',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,LBL,NMSPC_CD,OBJ_ID,VER_NBR) 
  VALUES ('Y','org.kuali.rice.student.bo.KualiStudentKimAttributes',KRIM_ATTR_DEFN_ID_S.NEXTVAL,'department','Department','KS-LUM',sys_guid(),1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR) 
  VALUES ('Y',KRIM_ATTR_DEFN_ID_S.CURRVAL,KRIM_TYP_ATTR_ID_S.NEXTVAL,KRIM_TYP_ID_S.CURRVAL,sys_guid(),'a',1)
/
