--Namespace
DELETE FROM KRNS_NMSPC_T WHERE NMSPC_CD = 'UMD-KS-CM'
/
DELETE FROM KRNS_NMSPC_T WHERE NMSPC_CD = 'UMD-KS-SYS'
/

INSERT INTO KRNS_NMSPC_T (NMSPC_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, APPL_NMSPC_CD)
  VALUES ('UMD-KS-CM', '67015bfe-e1f9-4f49-9d63-ded69033b3df', 1, 'UMD KS Curriculum Management System', 'Y', 'STUDENT')
/

INSERT INTO KRNS_NMSPC_T (NMSPC_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, APPL_NMSPC_CD)
  VALUES ('UMD-KS-SYS', 'd098c98c-eab3-4579-bd37-975c708ea0ff', 1, 'UMD Kuali Student System', 'Y', 'STUDENT')
/
  
-- kim module kim permissions
DELETE FROM KRIM_ROLE_PERM_T WHERE OBJ_ID = '28feec6b-5612-4b15-8f97-dbff19408815' AND ROLE_ID = '63'
/
DELETE FROM KRIM_ROLE_PERM_T WHERE OBJ_ID = '70711200-bb67-4423-81f1-87cb65d2a9b5' AND ROLE_ID = '63'
/
DELETE FROM KRIM_ROLE_PERM_T WHERE OBJ_ID = '2d2db450-03fa-49aa-9b9d-83090441aba1' AND ROLE_ID = '63'
/
DELETE FROM KRIM_ROLE_PERM_T WHERE OBJ_ID = '33201c1f-3095-4dee-8449-93479a984a76' AND ROLE_ID = '63'
/
DELETE FROM KRIM_PERM_T WHERE NMSPC_CD = 'UMD-KS-SYS'
/
DELETE FROM KRIM_PERM_ATTR_DATA_T WHERE ATTR_VAL = 'UMD-KS*'
/

INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR,NM)
  VALUES ('Y','UMD-KS-SYS','5a3c6127-7a29-4c24-ab38-083dd4a61f02',KRIM_PERM_ID_S.NEXTVAL,'35',1, 'Assign Role')
/

INSERT INTO KRIM_PERM_ATTR_DATA_T (VER_NBR,OBJ_ID,KIM_TYP_ID,KIM_ATTR_DEFN_ID,ATTR_DATA_ID,PERM_ID,ATTR_VAL)
  VALUES (1,'8d7fa68a-1e9e-4cc7-b2f9-8c24ec034678','20','4',KRIM_ATTR_DATA_ID_S.NEXTVAL,KRIM_PERM_ID_S.CURRVAL,'UMD-KS*')
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y','28feec6b-5612-4b15-8f97-dbff19408815',KRIM_PERM_ID_S.CURRVAL,'63',KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),KRIM_PERM_ID_S.CURRVAL,(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
  
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR,NM)
  VALUES ('Y','UMD-KS-SYS','f08ba771-5dd1-4f36-96f9-0f4f10821092',KRIM_PERM_ID_S.NEXTVAL,'36',1, 'Grant Permission')
/

INSERT INTO KRIM_PERM_ATTR_DATA_T (VER_NBR,OBJ_ID,KIM_TYP_ID,KIM_ATTR_DEFN_ID,ATTR_DATA_ID,PERM_ID,ATTR_VAL)
  VALUES (1,'d26b594b-7826-46dc-874a-ec1c031a199b','20','4',KRIM_ATTR_DATA_ID_S.NEXTVAL,KRIM_PERM_ID_S.CURRVAL,'UMD-KS*')
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y','70711200-bb67-4423-81f1-87cb65d2a9b5',KRIM_PERM_ID_S.CURRVAL,'63',KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),KRIM_PERM_ID_S.CURRVAL,(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/


INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR,NM)
  VALUES ('Y','UMD-KS-SYS','edf4f32c-9eb2-4d64-a0dd-4e8164d844de',KRIM_PERM_ID_S.NEXTVAL,'37',1, 'Grant Responsibility')
/

INSERT INTO KRIM_PERM_ATTR_DATA_T (VER_NBR,OBJ_ID,KIM_TYP_ID,KIM_ATTR_DEFN_ID,ATTR_DATA_ID,PERM_ID,ATTR_VAL)
  VALUES (1,'4a1ae76c-8499-410d-b1f6-2c4fdd20c869','20','4',KRIM_ATTR_DATA_ID_S.NEXTVAL,KRIM_PERM_ID_S.CURRVAL,'UMD-KS*')
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y','2d2db450-03fa-49aa-9b9d-83090441aba1',KRIM_PERM_ID_S.CURRVAL,'63',KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),KRIM_PERM_ID_S.CURRVAL,(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
  
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR,NM)
  VALUES ('Y','UMD-KS-SYS','5ce96258-c193-4e82-9c96-ae4fc80eb134',KRIM_PERM_ID_S.NEXTVAL,'38',1, 'Populate Group')
/

INSERT INTO KRIM_PERM_ATTR_DATA_T (VER_NBR,OBJ_ID,KIM_TYP_ID,KIM_ATTR_DEFN_ID,ATTR_DATA_ID,PERM_ID,ATTR_VAL)
   VALUES (1,'ce62da22-a783-4d5d-b4ac-df44afbdda8a','20','4',KRIM_ATTR_DATA_ID_S.NEXTVAL,KRIM_PERM_ID_S.CURRVAL,'UMD-KS*')
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y','33201c1f-3095-4dee-8449-93479a984a76',KRIM_PERM_ID_S.CURRVAL,'63',KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),KRIM_PERM_ID_S.CURRVAL,(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/


-- type 102 is department type
-- type 101 is college type

-- Roles
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PRE_REV_ROL01'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PCC_REV_ROL01'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PCC_REV_ROL02'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_CHR_REV_ROL01'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PRE_REV_ROL01'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PCC_REV_ROL01'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PCC_REV_ROL02'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_DEAN_REV_ROL01'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_AA_PRE_REV_ROL01'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_VPAC_REV_ROL01'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_VPAC_REV_ROL02'
/
DELETE FROM KRIM_ROLE_RSP_T WHERE OBJ_ID = 'UMDCM_WF_RSP_SCH_OFF_REV_ROL01'
/
DELETE FROM KRIM_RSP_T WHERE NMSPC_CD = 'UMD-KS-CM'
/
DELETE FROM KRIM_ROLE_T WHERE NMSPC_CD = 'UMD-KS-CM'
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR) 
	VALUES ('Y',(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='Department Type' AND NMSPC_CD='KS-LUM'),'UMD-KS-CM','UMDCM_WF_DEPT_CURRIC_MGR',KRIM_ROLE_ID_S.NEXTVAL,'Department Curriculum Manager',1)
/
INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR) 
	VALUES ('Y',(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='Department Type' AND NMSPC_CD='KS-LUM'),'UMD-KS-CM','UMDCM_WF_DEPT_PCC_MEM',KRIM_ROLE_ID_S.NEXTVAL,'Department PCC Member',1)
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y',(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='Department Type' AND NMSPC_CD='KS-LUM'),'UMD-KS-CM','UMDCM_WF_DEPT_PCC_CHAIR',KRIM_ROLE_ID_S.NEXTVAL,'Department PCC Chair',1)
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y',(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='Department Type' AND NMSPC_CD='KS-LUM'),'UMD-KS-CM','UMDCM_WF_DEPT_CHAIR',KRIM_ROLE_ID_S.NEXTVAL,'Department Chair',1)
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y',(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='College Type' AND NMSPC_CD='KS-LUM'),'UMD-KS-CM','UMDCM_WF_COLL_CURRIC_MGR',KRIM_ROLE_ID_S.NEXTVAL,'College Curriculum Manager',1)
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y',(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='College Type' AND NMSPC_CD='KS-LUM'),'UMD-KS-CM','UMDCM_WF_COLL_PCC_MEM',KRIM_ROLE_ID_S.NEXTVAL,'College PCC Member',1)
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y',(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='College Type' AND NMSPC_CD='KS-LUM'),'UMD-KS-CM','UMDCM_WF_COLL_PCC_CHAIR',KRIM_ROLE_ID_S.NEXTVAL,'College PCC Chair',1)
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y',(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='College Type' AND NMSPC_CD='KS-LUM'),'UMD-KS-CM','UMDCM_WF_COLL_DEAN',KRIM_ROLE_ID_S.NEXTVAL,'College Dean',1)
/
  
INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y','1','UMD-KS-CM','UMDCM_WF_ACDM_AFFR',KRIM_ROLE_ID_S.NEXTVAL,'Academic Affairs Curriculum Manager',1)
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y','1','UMD-KS-CM','UMDCM_WF_VPAC_MEM',KRIM_ROLE_ID_S.NEXTVAL,'VPAC Member',1)
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y','1','UMD-KS-CM','UMDCM_WF_PVST_REP',KRIM_ROLE_ID_S.NEXTVAL,'Provost Representative',1)
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y','1','UMD-KS-CM','UMDCM_WF_SCHED_OFF_CRS_REV',KRIM_ROLE_ID_S.NEXTVAL,'Scheduling Office Course Reviewer',1)
/

-- Scheduling Office Curriculum Manager
INSERT INTO KRIM_ROLE_T (ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, DESC_TXT, KIM_TYP_ID, ACTV_IND, LAST_UPDT_DT) 
  VALUES (KRIM_ROLE_ID_S.NEXTVAL, sys_guid(),'1','Scheduling Office Curriculum Manager', 'UMD-KS-CM','This role identifies scheduling officers for UMD-CM','1','Y',null)
/

-- Registrar Program Curriculum Manager
INSERT INTO KRIM_ROLE_T (ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, DESC_TXT, KIM_TYP_ID, ACTV_IND, LAST_UPDT_DT) 
  VALUES (KRIM_ROLE_ID_S.NEXTVAL, sys_guid(),'1','Registrar Program Curriculum Manager', 'UMD-KS-CM','This role identifies UMD-CM registrar for managing programs','1','Y',null)
/

-- Scheduling Office Student Employee
INSERT INTO KRIM_ROLE_T (ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, DESC_TXT, KIM_TYP_ID, ACTV_IND, LAST_UPDT_DT) 
  VALUES (KRIM_ROLE_ID_S.NEXTVAL, sys_guid(),'1','Scheduling Office Student Employee', 'UMD-KS-CM','This role identifies students in the scheduling office','1','Y',null)
/

-- Responsibilities
-- Department Pre-Review 
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
  VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Review','Y','1',0,'Responsibility for Department Pre Review','UMDCM_WF_RSP_DEPT_PRE_REV')
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PRE_REV_ATTR01'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluCreditCourseParentDocument','13','7','UMDCM_WF_RSP_DEPT_PRE_REV_ATTR01',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PRE_REV_ATTR02'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Department Pre Review','16','7','UMDCM_WF_RSP_DEPT_PRE_REV_ATTR02',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PRE_REV_ATTR03'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','41','7','UMDCM_WF_RSP_DEPT_PRE_REV_ATTR03',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PRE_REV_ATTR04'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','40','7','UMDCM_WF_RSP_DEPT_PRE_REV_ATTR04',KRIM_RSP_ID_S.CURRVAL,1)
/

INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_DEPT_PRE_REV_ROL01', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_DEPT_CURRIC_MGR'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PRE_REV_ACT01'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_DEPT_PRE_REV_ACT01',1,'A','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')
/
 
  
--  Department PCC Review
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
  VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Review','Y','1',0,'Responsibility for Department PCC Review','UMDCM_WF_RSP_DEPT_PCC_REV')
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PCC_REV_ATTR01'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluCreditCourseParentDocument','13','7','UMDCM_WF_RSP_DEPT_PCC_REV_ATTR01',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PCC_REV_ATTR02'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Department PCC Review','16','7','UMDCM_WF_RSP_DEPT_PCC_REV_ATTR02',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PCC_REV_ATTR03'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','41','7','UMDCM_WF_RSP_DEPT_PCC_REV_ATTR03',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PCC_REV_ATTR04'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','40','7','UMDCM_WF_RSP_DEPT_PCC_REV_ATTR04',KRIM_RSP_ID_S.CURRVAL,1)  
/

-- PCC Member (Gets FYI)
INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_DEPT_PCC_REV_ROL01', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_DEPT_PCC_MEM'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PCC_REV_ACT01'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_DEPT_PCC_REV_ACT01',1,'F','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/

-- PCC Chair (Gets Approve)
INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_DEPT_PCC_REV_ROL02', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_DEPT_PCC_CHAIR'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_PCC_REV_ACT02'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_DEPT_PCC_REV_ACT02',1,'A','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/

-- Department Chair Review  
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
  VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Review','Y','1',0,'Responsibility for Department Chair Review','UMDCM_WF_RSP_DEPT_CHR_REV')
/
  
DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_CHR_REV_ATTR01'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluCreditCourseParentDocument','13','7','UMDCM_WF_RSP_DEPT_CHR_REV_ATTR01',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_CHR_REV_ATTR02'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Department Chair Review','16','7','UMDCM_WF_RSP_DEPT_CHR_REV_ATTR02',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_CHR_REV_ATTR03'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','41','7','UMDCM_WF_RSP_DEPT_CHR_REV_ATTR03',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_CHR_REV_ATTR04'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','40','7','UMDCM_WF_RSP_DEPT_CHR_REV_ATTR04',KRIM_RSP_ID_S.CURRVAL,1)  
/

INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_DEPT_CHR_REV_ROL01', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_DEPT_CHAIR'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_DEPT_CHR_REV_ACT01'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_DEPT_CHR_REV_ACT01',1,'A','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/
    
-- College Pre Review  
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
  VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Review','Y','1',0,'Responsibility for College Pre Review','UMDCM_WF_RSP_COLL_PRE_REV')
/
  
DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PRE_REV_ATTR01'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluCreditCourseParentDocument','13','7','UMDCM_WF_RSP_COLL_PRE_REV_ATTR01',KRIM_RSP_ID_S.CURRVAL,1)
/
  
DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PRE_REV_ATTR02'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'College Pre Review','16','7','UMDCM_WF_RSP_COLL_PRE_REV_ATTR02',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PRE_REV_ATTR03'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','41','7','UMDCM_WF_RSP_COLL_PRE_REV_ATTR03',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PRE_REV_ATTR04'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','40','7','UMDCM_WF_RSP_COLL_PRE_REV_ATTR04',KRIM_RSP_ID_S.CURRVAL,1)  
/

INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_COLL_PRE_REV_ROL01', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_COLL_CURRIC_MGR'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PRE_REV_ACT01'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_COLL_PRE_REV_ACT01',1,'A','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/

-- College PCC Review  
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
  VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Review','Y','1',0,'Responsibility for College PCC Review','UMDCM_WF_RSP_COLL_PCC_REV')
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PCC_REV_ATTR01'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluCreditCourseParentDocument','13','7','UMDCM_WF_RSP_COLL_PCC_REV_ATTR01',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PCC_REV_ATTR02'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'College PCC Review','16','7','UMDCM_WF_RSP_COLL_PCC_REV_ATTR02',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PCC_REV_ATTR03'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','41','7','UMDCM_WF_RSP_COLL_PCC_REV_ATTR03',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PCC_REV_ATTR04'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','40','7','UMDCM_WF_RSP_COLL_PCC_REV_ATTR04',KRIM_RSP_ID_S.CURRVAL,1)  
/

-- PCC Member (Gets FYI)
INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_COLL_PCC_REV_ROL01', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_COLL_PCC_MEM'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PCC_REV_ACT01'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_COLL_PCC_REV_ACT01',1,'F','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')
/
  
-- PCC Chair (Gets Approve)  
INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_COLL_PCC_REV_ROL02', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_COLL_PCC_CHAIR'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_PCC_REV_ACT02'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_COLL_PCC_REV_ACT02',1,'A','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/

 -- College Dean Review  
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
  VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Review','Y','1',0,'Responsibility for College Dean Review','UMDCM_WF_RSP_COLL_DEAN_REV')
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_DEAN_REV_ATTR01'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluCreditCourseParentDocument','13','7','UMDCM_WF_RSP_COLL_DEAN_REV_ATTR01',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_DEAN_REV_ATTR02'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'College Dean Review','16','7','UMDCM_WF_RSP_COLL_DEAN_REV_ATTR02',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_DEAN_REV_ATTR03'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','41','7','UMDCM_WF_RSP_COLL_DEAN_REV_ATTR03',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_DEAN_REV_ATTR04'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','40','7','UMDCM_WF_RSP_COLL_DEAN_REV_ATTR04',KRIM_RSP_ID_S.CURRVAL,1)  
/

INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_COLL_DEAN_REV_ROL01', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_COLL_DEAN'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_COLL_DEAN_REV_ACT01'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_COLL_DEAN_REV_ACT01',1,'A','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/

  
-- Academic Affairs Pre Review
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
  VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Review','Y','1',0,'Responsibility for Academic Affairs Pre Review','UMDCM_WF_RSP_AA_PRE_REV')
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_AA_PRE_REV_ATTR01'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluCreditCourseParentDocument','13','7','UMDCM_WF_RSP_AA_PRE_REV_ATTR01',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_AA_PRE_REV_ATTR02'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Academic Affairs Pre Review','16','7','UMDCM_WF_RSP_AA_PRE_REV_ATTR02',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_AA_PRE_REV_ATTR03'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','41','7','UMDCM_WF_RSP_AA_PRE_REV_ATTR03',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_AA_PRE_REV_ATTR04'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','40','7','UMDCM_WF_RSP_AA_PRE_REV_ATTR04',KRIM_RSP_ID_S.CURRVAL,1)  
/

INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_AA_PRE_REV_ROL01', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_ACDM_AFFR'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_AA_PRE_REV_ACT01'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_AA_PRE_REV_ACT01',1,'A','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/


-- VPAC Academic Affairs Review
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
  VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Review','Y','1',0,'Responsibility for VPAC Academic Affairs Review','UMDCM_WF_RSP_VPAC_REV')
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_VPAC_REV_ATTR01'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluCreditCourseParentDocument','13','7','UMDCM_WF_RSP_VPAC_REV_ATTR01',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_VPAC_REV_ATTR02'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'VPAC Academic Affairs Review','16','7','UMDCM_WF_RSP_VPAC_REV_ATTR02',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_VPAC_REV_ATTR03'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','41','7','UMDCM_WF_RSP_VPAC_REV_ATTR03',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_VPAC_REV_ATTR04'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','40','7','UMDCM_WF_RSP_VPAC_REV_ATTR04',KRIM_RSP_ID_S.CURRVAL,1)  
/

-- VPAC Members get FYI 
INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_VPAC_REV_ROL01', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_VPAC_MEM'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_VPAC_REV_ACT01'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_VPAC_REV_ACT01',1,'F','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/

-- Provost or Delegate get Approve
INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_VPAC_REV_ROL02', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_PVST_REP'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_VPAC_REV_ACT02'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_VPAC_REV_ACT02',1,'A','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/
  
-- Scheduling Office Processing
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
  VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Review','Y','1',0,'Responsibility for Scheduling Office Processing','UMDCM_WF_RSP_SCH_OFF_REV')
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_SCH_OFF_REV_ATTR01'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluCreditCourseParentDocument','13','7','UMDCM_WF_RSP_SCH_OFF_REV_ATTR01',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_SCH_OFF_REV_ATTR02'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Scheduling Office Processing','16','7','UMDCM_WF_RSP_SCH_OFF_REV_ATTR02',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_SCH_OFF_REV_ATTR03'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','41','7','UMDCM_WF_RSP_SCH_OFF_REV_ATTR03',KRIM_RSP_ID_S.CURRVAL,1)
/

DELETE FROM KRIM_RSP_ATTR_DATA_T WHERE OBJ_ID = 'UMDCM_WF_RSP_SCH_OFF_REV_ATTR04'
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'false','40','7','UMDCM_WF_RSP_SCH_OFF_REV_ATTR04',KRIM_RSP_ID_S.CURRVAL,1)  
/

INSERT INTO KRIM_ROLE_RSP_T (ACTV_IND,OBJ_ID,RSP_ID,ROLE_ID,ROLE_RSP_ID,VER_NBR) 
  VALUES ('Y','UMDCM_WF_RSP_SCH_OFF_REV_ROL01', KRIM_RSP_ID_S.CURRVAL, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE OBJ_ID='UMDCM_WF_SCHED_OFF_CRS_REV'),KRIM_ROLE_RSP_ID_S.NEXTVAL,1)
/

DELETE FROM KRIM_ROLE_RSP_ACTN_T WHERE OBJ_ID = 'UMDCM_WF_RSP_SCH_OFF_REV_ACT01'
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID,OBJ_ID,VER_NBR,ACTN_TYP_CD,ACTN_PLCY_CD,ROLE_MBR_ID,ROLE_RSP_ID,FRC_ACTN) 
  VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL,'UMDCM_WF_RSP_SCH_OFF_REV_ACT01',1,'A','F','*',KRIM_ROLE_RSP_ID_S.CURRVAL,'Y')  
/

-- Assign Create Course By Proposal permission to the Registrar Program Curriculum Manager role
INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND)
  VALUES (KRIM_ROLE_PERM_ID_S.NEXTVAL, sys_guid(), 1, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Registrar Program Curriculum Manager'), (select perm_id from krim_perm_t where nm = 'Create Course By Proposal'), 'Y')
/
-- Assign KS Admin Screens permission to the Registrar Program Curriculum Manager role
INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND)
  VALUES (KRIM_ROLE_PERM_ID_S.NEXTVAL, sys_guid(), 1, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Registrar Program Curriculum Manager'), (select perm_id from krim_perm_t where nm = 'Use Curriculum Review'), 'Y')
/

-- Assign Create Course By Proposal permission to the Registrar Program Curriculum Manager role
INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND)
  VALUES (KRIM_ROLE_PERM_ID_S.NEXTVAL, sys_guid(), 1, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Scheduling Office Curriculum Manager'), (select perm_id from krim_perm_t where nm = 'Create Course By Proposal'), 'Y')
/
-- Assign KS Admin Screens permission to the Registrar Program Curriculum Manager role
INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND)
  VALUES (KRIM_ROLE_PERM_ID_S.NEXTVAL, sys_guid(), 1, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Scheduling Office Curriculum Manager'), (select perm_id from krim_perm_t where nm = 'Use Curriculum Review'), 'Y')
/


-- *** UMD CM PERMISSION TYPE SERVICES ***

--NOTE: This role is in the umd-rice kim.sql file
-- Derived Role Faculty Staff Grad Assistant Role Permisson Type
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y',KRIM_TYP_ID_S.NEXTVAL,'Derived Role: KS Faculty Staff Grad Assistant Role Type','UMD-RICE',sys_guid(),'facultyStaffGradAssistantRoleTypeService',1)
/

-- *** UMD CM ROLES ***

-- UMD-CM User Derived Role 
INSERT INTO KRIM_ROLE_T (ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, DESC_TXT, KIM_TYP_ID, ACTV_IND, LAST_UPDT_DT) 
  VALUES (KRIM_ROLE_ID_S.NEXTVAL, sys_guid(),'1','Derived Role: UMD-CM Users', 'UMD-KS-CM','This role identifies users who are users of UMD CM',(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='Derived Role: KS Faculty Staff Grad Assistant Role Type'),'Y',null)
/
-- Assign UMD-CM Role to KS CUM User Role
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES (KRIM_ROLE_ID_S.CURRVAL,'R',sys_guid(),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM User'),KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/

--- *** UMD CM Authorizaion Spreadsheet Inserts after 12/13/12

-- Assign Create Course By Admin Proposal Perm to SOCM Role  
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Create Course By Admin Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Scheduling Office Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

--- *** UMD CM Authorizaion Spreadsheet Inserts 12/14/12

-- Assign Modify Course By Admin Proposal Perm to AACM & RPCM roles
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Course By Admin Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Registrar Program Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Course By Admin Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Academic Affairs Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/


-- Assign Modify Program By Proposal Perm to AACM & RPCM roles
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Program By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Registrar Program Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Program By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Academic Affairs Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/


-- Assign Use Curriculum Review Permission Perm to AACM & RPCM roles
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Use Curriculum Review'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Registrar Program Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Use Curriculum Review'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Academic Affairs Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Use Curriculum Review'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/


-- Assign Use Curriculum Review Permission Perm to AACM & RPCM roles
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Clu Without Version Dialog'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Registrar Program Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Clu Without Version Dialog'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Academic Affairs Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Clu Without Version Dialog'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

