-- UMD CM Admin Role (For exception routing, This is different from Kuali Student CM Admin role, which UMD is not utilizing)
INSERT INTO KRIM_ROLE_T (ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, DESC_TXT, KIM_TYP_ID, ACTV_IND, LAST_UPDT_DT)
  VALUES (KRIM_ROLE_ID_S.NEXTVAL, sys_guid(),'1','UMD-CM Admin', 'UMD-KS-CM','UMD admin role for CM, with view privileges for admin functions & CM exception routing responsibility.', '1','Y',null)
/

-- TODO: Add Screen Permissions to UMD-CM Admin Role





-- *** Assign KIM Management Permissions for UMD Namespace to KS IDM Admin Role ***

-- Grant KS KIM Assign Role permission to KS IDM Admin Role
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE KRIM_PERM_T.NMSPC_CD='UMD-KS-SYS' AND NM='Assign Role'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Kuali Student IDM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

-- Grant KIM Grant Permission Permission to KS IDM Admin Role
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE KRIM_PERM_T.NMSPC_CD='UMD-KS-SYS' AND NM='Grant Permission'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Kuali Student IDM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

-- Grant KIM Grant Responsibility Permission to KS IDM Admin Role
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE KRIM_PERM_T.NMSPC_CD='UMD-KS-SYS' AND NM='Grant Responsibility'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Kuali Student IDM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

-- Grant KIM Populate Group Permission to KS IDM Admin Role
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE KRIM_PERM_T.NMSPC_CD='UMD-KS-SYS' AND NM='Populate Group'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Kuali Student IDM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/



-- *** CM Workflow Exception Routing Responsibility to KS Admin Role ***
INSERT INTO KRIM_RSP_T (RSP_ID,NMSPC_CD,NM,ACTV_IND,RSP_TMPL_ID,VER_NBR,DESC_TXT,OBJ_ID) 
VALUES (KRIM_RSP_ID_S.NEXTVAL,'UMD-KS-CM','Resolve KS CM Exception','Y','2',1,'Responsibility for Kuali Student CM Exception Routing',SYS_GUID())
/

INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,RSP_ID,VER_NBR) 
VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'CluParentDocument','13','54',sys_guid(),KRIM_RSP_ID_S.CURRVAL,1)
/

INSERT INTO KRIM_ROLE_RSP_T (ROLE_RSP_ID, OBJ_ID, VER_NBR, ROLE_ID, RSP_ID, ACTV_IND)
VALUES (KRIM_ROLE_RSP_ID_S.NEXTVAL, SYS_GUID(), 1, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='UMD-CM Admin'), KRIM_RSP_ID_S.CURRVAL, 'Y')
/

INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID, OBJ_ID, VER_NBR, ACTN_TYP_CD, PRIORITY_NBR, ACTN_PLCY_CD, ROLE_MBR_ID, ROLE_RSP_ID, FRC_ACTN)
VALUES (KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL, SYS_GUID(), 1, 'A', null, 'F', '*', KRIM_ROLE_RSP_ID_S.CURRVAL, 'Y')
/
