
--- The following are templates

-- Assign Create Program By Admin Perm to AACM & RPCM roles
--INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
-- VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM=''),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Registrar Program Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
--/
--INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
--  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM=''),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Academic Affairs Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
--/

--KSCM-1209
-- Assign Use Curriculum Review Screens By Admin Perm to AACM, SOCM, PR roles
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Use Curriculum Review'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Scheduling Office Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Use Curriculum Review'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Academic Affairs Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Use Curriculum Review'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

--KSCM-307
-- Assign Create Course By Admin Proposal to AACM, RPCM roles
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Create Course By Admin Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Registrar Program Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Create Course By Admin Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Academic Affairs Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

-- Assign Create Program By Proposal to AACM, RPCM roles
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Create Program By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Registrar Program Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Create Program By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Academic Affairs Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

