--push in role->permission mappings that were in RRR QA but not in PROD
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Create Course By Admin Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Create Course By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Create Program By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Clu Without Version Dialog'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Course By Admin Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Course By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Program By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Use Curriculum Review'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='UMD-RICE' AND NM='View Admin Tab'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Create Course By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM User'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR) VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Course By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='KS-SYS' AND ROLE_NM='Kuali Student CM User'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

-- Delete any duplicated role - permission rows
DELETE FROM KRIM_ROLE_PERM_T A WHERE A.rowid > ANY ( SELECT B.rowid FROM KRIM_ROLE_PERM_T B WHERE A.ROLE_ID = B.ROLE_ID AND A.PERM_ID = B.PERM_ID AND A.ACTV_IND='Y' AND B.ACTV_IND='Y' ) 
/
    
-- clear out any null foreign keys to roles or perms
DELETE FROM KRIM_ROLE_PERM_T WHERE PERM_ID IS NULL OR ROLE_ID IS NULL 
/

-- push in changes that were retroactively added to the update scripts
UPDATE KRIM_PERM_TMPL_T SET KRIM_PERM_TMPL_T.KIM_TYP_ID= ( SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='Default' ) WHERE NMSPC_CD='KS-SYS' AND NM='Use Screen'
/

UPDATE KRIM_TYP_ATTR_T SET KIM_TYP_ID= ( SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM='Default' ) WHERE KIM_ATTR_DEFN_ID IN ( SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD='KS-SYS' AND NM='screenComponent' )
/
