INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Create Course By Admin Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Modify Course By Admin Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Create Program By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Modify Program By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Use Create Program By Proposal'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Use Browse Program Screen'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Use Find Program Screen'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Use Find Program Proposal Screen'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Use View Core Programs Screen'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Use View Credential Programs Screen'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Use View Course Set Management Screens'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Use LO Category Screens'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Use Dependency Analysis Screen'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/

INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(), (SELECT PERM_ID FROM KRIM_PERM_T where nm = 'Open Create Course Route Status R'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM='Provost Representative'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
