--Use Course Modify Screens
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Clu Without Version Dialog'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Scheduling Office Student Employee'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Clu Without Version Dialog'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Academic Affairs Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',sys_guid(),(SELECT PERM_ID FROM KRIM_PERM_T WHERE NMSPC_CD='KS-SYS' AND NM='Modify Clu Without Version Dialog'),(SELECT ROLE_ID FROM KRIM_ROLE_T WHERE NMSPC_CD='UMD-KS-CM' AND ROLE_NM='Scheduling Office Curriculum Manager'),KRIM_ROLE_PERM_ID_S.NEXTVAL,1)
/
