
/*
 * 
 */
package org.kuali.student.loader.rules;

import org.kuali.student.r2.lum.clu.service.CluService;
import org.kuali.student.r2.lum.util.constants.CluServiceConstants;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.2.10
 * Wed Sep 08 11:26:43 EDT 2010
 * Generated source version: 2.2.10
 * 
 */
@WebServiceClient (name = "CluService",
                   targetNamespace = CluServiceConstants.NAMESPACE)
public class CluService_Service extends Service
{

 public final static URL WSDL_LOCATION;
 public final static QName SERVICE = new QName (
   "http://student.kuali.org/wsdl/clu", "CluService");
 public final static QName CluServicePort = new QName (
   "http://student.kuali.org/wsdl/clu", "CluServicePort");

 static
 {
  URL url = null;
  try
  {
   url =
   new URL (
     "file:/C:/java/training/aggregate/ks-api/ks-lum-api/src/main/resources/META-INF/wsdl/CourseService.wsdl");
  }
  catch (MalformedURLException e)
  {
   System.err.println (
     "Can not initialize the default wsdl from file:/C:/java/training/aggregate/ks-api/ks-lum-api/src/main/resources/META-INF/wsdl/CourseService.wsdl");
   // e.printStackTrace();
  }
  WSDL_LOCATION = url;
 }

 public CluService_Service(URL wsdlLocation)
 {
  super (wsdlLocation, SERVICE);
 }

 public CluService_Service(URL wsdlLocation, QName serviceName)
 {
  super (wsdlLocation, serviceName);
 }

 public CluService_Service()
 {
  super (WSDL_LOCATION, SERVICE);
 }

 /**
  *
  * @return
  *     returns CourseService
  */
 @WebEndpoint (name = "CluServicePort")
 public CluService getServicePort ()
 {
  return super.getPort (CluServicePort, CluService.class);
 }

 /**
  *
  * @param features
  *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
  * @return
  *     returns CourseService
  */
 @WebEndpoint (name = "CluServicePort")
 public CluService getServicePort (WebServiceFeature... features)
 {
  return super.getPort (CluServicePort, CluService.class, features);
 }
}
