DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'UMDCM_CRS';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE UMDCM_CRS CASCADE CONSTRAINTS PURGE'; END IF;
END;
/
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'SISCM_IMPORT_QUEUE';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE SISCM_IMPORT_QUEUE CASCADE CONSTRAINTS PURGE'; END IF;
END;
/
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'SISCM_BATCH_JOB';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE SISCM_BATCH_JOB CASCADE CONSTRAINTS PURGE'; END IF;
END;
/
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'SISCM_DIFF';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE SISCM_DIFF CASCADE CONSTRAINTS PURGE'; END IF;
END;
/
BEGIN
   for x in (select sequence_name
             from   user_sequences
              where sequence_name in ('BATCH_SIS_TO_CM_S'))
   loop
      execute immediate 'drop sequence '||x.sequence_name;
   END loop;
END;
/

create or replace function checksum(string in varchar2) return varchar2
is
begin
  return utl_raw.cast_to_varchar2(UTL_ENCODE.BASE64_ENCODE(UTL_RAW.cast_to_raw(dbms_obfuscation_toolkit.md5(input_string => string))));
end;
/

CREATE
    TABLE UMDCM_CRS
    (
        ID VARCHAR2(255) NOT NULL,
        CRS VARCHAR2(8) NOT NULL,
        TRM VARCHAR2(6) NOT NULL,
        TRM_END VARCHAR2(6),
        MIN_CR NUMBER(4,2),
        MAX_CR NUMBER(4,2),
        GRD_METH VARCHAR2(6),
        CRS_TITLE VARCHAR2(120),
        TRANSCR_TITLE VARCHAR2(24),
        CRS_DESC VARCHAR2(4000),
        CRS_REQS VARCHAR2(4000),
        STATUS_IND VARCHAR2(1),
        MOD_DT TIMESTAMP(6),
        MOD_ID VARCHAR2(24),
        CRS_ID VARCHAR2(255) NOT NULL,
		GENED VARCHAR2(500),
		DIVERSITY VARCHAR2(500),
		CORE VARCHAR2(500),
		ADMIN_STAT VARCHAR2(1),
        LECTURE_HRS NUMBER,
        LAB_HRS NUMBER,
        EXPERIMENTAL_HRS NUMBER,
        DISCUSSION_HRS NUMBER,
        UPLOAD_DT TIMESTAMP(6),
        CONSTRAINT UMDCM_CRS_pk PRIMARY KEY (ID),
        CONSTRAINT UMDCM_CRS_ix1 UNIQUE (CRS, TRM)
    )
/
CREATE
    TABLE SISCM_BATCH_JOB
    (
        ID NUMBER(19,0) NOT NULL,
        EXECUTION_DT TIMESTAMP,
        MOD_DT TIMESTAMP,
        CONSTRAINT SISCM_BATCH_JOB_PK PRIMARY KEY (ID) 
        
    )
/
CREATE
    TABLE SISCM_DIFF
    (
        CRS VARCHAR2(8) NOT NULL,
    	START_TRM VARCHAR2(6) NOT NULL,
    	SIS_MD5_HASH VARCHAR(32),
    	MOD_DT TIMESTAMP,
    	CONSTRAINT SISCM_DIFF1 PRIMARY KEY (CRS,START_TRM)
     )
/
CREATE
    TABLE SISCM_IMPORT_QUEUE
    (
        ID VARCHAR2(255) NOT NULL,
        BATCH_JOB_ID NUMBER(19,0) NOT NULL,
        ERROR_LOG CLOB,
		HASH VARCHAR2(24),
		OPERATION VARCHAR2(1),
		AP_CRS VARCHAR2(8),
        START_TRM VARCHAR2(6),  
        END_TRM VARCHAR2(6),
        TRANS_TITLE VARCHAR2(24),
        FORMAL_TITLE VARCHAR2(120),
        TXT40  VARCHAR2(4000),
        MIN_CR  VARCHAR2(22),
	    MAX_CR  VARCHAR2(22),
	    GRD_METH  VARCHAR2(6),
	    ADMIN_STAT  VARCHAR2(1),
	    CORE  VARCHAR2(100),
	    DIVERISTY  VARCHAR2(100),
	    GENEDCODES  VARCHAR2(100),
	  	LEARNING_OUTCOMES VARCHAR2(4000),
	  	MOD_DT TIMESTAMP,
        CONSTRAINT SISCM_IMPORT_QUEUE_CRS1 PRIMARY KEY (ID),
        CONSTRAINT FK_BATCH_JOB_ID FOREIGN KEY (BATCH_JOB_ID) REFERENCES SISCM_BATCH_JOB(ID)
  
    )
/
create sequence BATCH_SIS_TO_CM_S
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    NOCACHE
/
